# Generated by Django 4.0.5 on 2022-08-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_group',
            name='e_maker',
            field=models.CharField(default='', max_length=150),
        ),
    ]
