# Generated by Django 4.0.5 on 2022-08-02 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0002_e_group_e_maker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senter', models.CharField(default='', max_length=150)),
                ('msg', models.TextField()),
                ('crt_time', models.DateTimeField(default=datetime.datetime(2022, 8, 2, 10, 4, 11, 823277))),
            ],
        ),
    ]
