# Generated by Django 4.0.5 on 2022-08-02 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0004_message_group_alter_message_crt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='maker',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='message',
            name='crt_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 13, 35, 43, 853486)),
        ),
    ]
